### PR TITLE
Initial scenarios contribution

### PR DESCRIPTION
**Pull request by erandermsft**
Messed this up somehow, think it was when I switched between Windows and WSL before committing. For some reason it then decided that all files in the repo were changed. 

The only real change is the addition of scenarios.md :)

### CODE REVIEW

**Comment by pelithne** [comment]
It looks like your second commit does not add anything (expect that it adds everything... again). 

What a great opportunity to refresh those "git rebase" skills! You should be able to do:
````
git checkout <din branch>
git rebase -i HEAD~2
````
and then (in the text editor that should open) replace the **pick** with **drop** on the last commit. Then save.

After this you can do a git push --force to your origin. That should update the PR automagically, if I remember...

**Comment by pelithne** [comment]
Perfect! LGTM! :thumbsup:

**Comment by erandermsft** [comment]
So let's merge it to master then? :) (I don't have write access)

**Comment by pelithne** [comment]
:-) (sorry about the access issue...)

**Pull request merged**
